---
title: "example"
format: 
  html: default
  pdf: default
editor: visual
---

## Assignment 2: git, GitHub, and the command line interface

1\. Create a new RStudio Project. In this folder, create a simple qmd file called that can be knitted into a HTML file. Show the result of the example.qmd knitted file.

-   create a new RStudio Project in the directory named "etc5513_assignment2"

-   create a new example.qmd file and change the format to html and pdf as a default.

2\. From the command line interface, initialise this folder as a git repository and push it to the GitHub classroom repository.

-   git clone follow by SSH URL

-   git add .

-   git commit -m "commit statement; add project and qmd file"

-   git push origin main

3\. Create a new branch called testbranch. Modify the file example.qmd and add the changes to both the local and remote repositories.

-   git branch testbranch

-   git switch testbranch

-   git add example.qmd

-   git commit -m "modified example.qmd"

-   git push origin testbranch

4\. Create a folder called data, and add the data from Assignment 1 to that folder. Amend the previous commit to include the data folder. Push this amended commit to the remote.

-   add the new folder named data and place the data from assignment1

-   git add .

-   git commit -m "added new data folder"

-   git push origin testbranch

5\. Switch back to the main branch and modify example.qmd in a different way such that it will conflict with testbranch. Commit and push these changes.git switch main

-   update change on example.qmd file

-   git add .

-   git commit -m "modified example.qmd on main"

-   git push origin main

6\. Merge the changes in testbranch onto main Show the conflict and fixing the merge conflict. Push the changes to GitHub, showing the status and changes in GitHub.

-   git branch to make sure you are on the main branch

-   (if not) use git switch branch

-   git merge testbranch

-   fix the conclict then

-   git add .

-   git commit -m "conflict resolved"

-   git push origin main

7\. Tag this commit v1.0 on main using an annotated tag.

8\. Delete branch testbranch locally and on the remote.
